[features]
seeds = false
skip-lint = false
[programs.localnet]
hello = "5eKArngzHduTsRLhcszUEifwtRSpYg5d6Ad41Sc1bKx7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/yangjiefeng/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
